DROP TABLE RESERVATION;
DROP TABLE PONEY;
DROP TABLE ADHERANT;
DROP TABLE MONITEUR;

CREATE TABLE ADHERANT (
    ipA INT PRIMARY KEY,
    nomA VARCHAR(20),
    prenomA VARCHAR(20),
    telA VARCHAR(15) UNIQUE,
    poid INT
);

CREATE TABLE MONITEUR (
    idM INT PRIMARY KEY,
    nomM VARCHAR(20),
    prenomM VARCHAR(20),
    telM VARCHAR(15) UNIQUE
);

CREATE TABLE PONEY (
    idP INT PRIMARY KEY,
    nomP VARCHAR(20),
    capacite INT
);

CREATE TABLE RESERVATION (
    dateR DATETIME,
    idA INT,
    idP INT,
    idM INT,
    duree INT,
    individuel BOOLEAN,
    FOREIGN KEY (idA) REFERENCES ADHERANT(ipA),
    FOREIGN KEY (idM) REFERENCES MONITEUR(idM),
    FOREIGN KEY (idP) REFERENCES PONEY(idP),
    PRIMARY KEY (dateR, idA, idP, idM)
);
