DROP TABLE RESERVATION;
DROP TABLE ADHERANT;
DROP TABLE MONITEUR;
DROP TABLE PONEY;

DROP FUNCTION IF EXISTS check_nbr_par;
DROP FUNCTION IF EXISTS check_capa;
DROP FUNCTION IF EXISTS dispo_moniteur;
DROP FUNCTION IF EXISTS dispo_poney;
DROP FUNCTION IF EXISTS check_repos;